language: node_js
sudo: false
env:
  - CXX=g++-4.8
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
script: npm run lint && npm test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
